name: Build RPM & Publish DNF repo

on:
  push:
    tags: ['v*']         # build when a version tag is pushed
  workflow_dispatch: {}  # manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: rockylinux:9   # <— swap UBI9 -> Rocky 9

    steps:
      - name: Install tools
        run: dnf -y install git rpm-build which tar gzip createrepo_c

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Vars from tag
        id: vars
        run: |
          TAG="${GITHUB_REF_NAME:-v0.0.0}"
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT
          echo "release=1" >> $GITHUB_OUTPUT

      - name: Build RPM
        run: |
          rpmbuild -ba SPECS/rhcsa-trainer.spec \
            --define "_sourcedir $GITHUB_WORKSPACE/SOURCES" \
            --define "version ${{ steps.vars.outputs.version }}" \
            --define "release ${{ steps.vars.outputs.release }}"

      - name: Stage EL9 repo dir
        run: |
          mkdir -p repo/el9
          cp -v ~/rpmbuild/RPMS/noarch/*.el9*.rpm repo/el9/ || true
          createrepo_c repo/el9

      - name: Publish to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: repo
          keep_files: true
